services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  auth-service:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
