services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready -U user -d authdb"]
      interval: 3s
      timeout: 5s
      retries: 5

  auth-service:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
